name: CI/CD Pipeline

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint
      run: pylint your_module.py

    - name: Run tests
      run: pytest tests/

    - name: Compute Code Metrics
      run: python code_metrics.py

    - name: Upload Code Metrics
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: code-metrics
        path: code_metrics.json

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: reports/

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.build-test.result == 'success'
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your deployment scripts here


